### ISSUE TITLE
Is it possible to use a non-interactive setup with service_account.json file?

### ISSUE THREAD

**Issue by MatiasManevi** [Lykos153/git-annex-remote-googledrive#97]
Is there a way to make `git-annex-remote-googledrive setup` non-interactive?

I am trying to use this tool inside a github workflow so I can setup git annex, set the remote (it is a gdrive remote) and pull some data from it to be inserted in a docker image during the process. 

This is somewhat what I am trying

```
name: Benchmark CI

on:
  push:
    branches:
      - main

jobs:
  run-benchmark:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git-annex
          sudo pip3 install git-annex-remote-googledrive

      - name: Configure Git identity
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Configure Google Drive access
        run: |
          mkdir -p ~/.config/git-annex
          echo "$GDRIVE_CREDENTIALS" > ~/.config/git-annex/service-account-key.json
        env:
          GDRIVE_CREDENTIALS: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}

      - name: Initialize git-annex
        run: |
          git annex init
          git annex initremote google type=external externaltype=googledrive prefix=git-annex encryption=none mac=HMACSHA512

      - name: Debug Annex Remote
        run: |
          git annex info
          git annex whereis

      - name: Fetch files from Google Drive
        run: |
          git annex get script.js || echo "File downloaded."

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{USER]}/test-sh-runners:${{ github.sha }}
```

When my self hosted runner runs the workflow it fails on initializing git annex

```
##[group***Run git annex init
git annex init
git annex initremote google type=external externaltype=googledrive prefix=git-annex encryption=none mac=HMACSHA51[2](https://github.com/Ekumen-OS/beluga_benchmarks/actions/runs/12300972917/job/34330441353#step:6:2)
shell: /usr/bin/bash -e ***0***
##[endgroup***
  Remote origin not usable by git-annex; setting annex-ignore
init  

  https://github.com/Ekumen-OS/beluga_benchmarks/config download failed: Not Found
ok
(recording state in git...)
git-annex: No Credentials found. Run 'git-annex-remote-googledrive setup' in order to authenticate.
initremote google 
failed
initremote: 1 failed
##[error***Process completed with exit code 1.
```

I cannot depend on running `git-annex-remote-googledrive setup` manually since I want this to work inside a github workflow. Is there a reasonable way to achieve that? Thanks!
